### ISSUE TITLE
Doesn't work in Wayland-Session

### ISSUE THREAD

**Issue by thebunnyrules** [dsboger/gnome-shell-extension-window-switcher-launcher#1]
Did you test this extension in Wayland? Window switcher doesn't seem to be customization in the Wayland session the way it was under X.

**Comment by dsboger-zz** [comment]
I tested and it works fine for me. I'll need some more information.

What happens when you open the window switcher? Does it not show the launchers? Does it not show at all? Also, what version of GNOME Shell you are using?

Ideally, it would be great if you could paste related log messages here too. You can get them using GNOME Logs application. Look for messages containing the extension ID (e.g. gnome-shell-extension-window-switcher-launcher).

Thanks for reporting!

**Comment by thebunnyrules** [comment]
Hi, thanks for get back to me. The extension is activated but no, the launchers don't show up at all (even after I logged out and back). They should come up when I press alt tab, right? 

I'm using gnome-shell 3.26.2 but the issue was present in 3.26.1 as well. I'll re-install the extensions and have a look at the logs.

**Comment by thebunnyrules** [comment]
I checked the logs. Beyond the logs of the installs, the only entry says 'no app for changed  gnome-shell-extension-window-switcher-launcher.dsboger@gmail'

**Comment by thebunnyrules** [comment]
I checked the logs. Beyond the logs of the installs, the only entry says 'no app for changed  gnome-shell-extension-window-switcher-launcher.dsboger@gmail'

**Comment by dsboger-zz** [comment]
Well, as the log is not helpful, please describe how exactly is the extension not working: does the window switcher appear? Is it lacking the launchers? 

Also, did you install this extension from extensions.gnome.org, GNOME Software or directly from GitHub?

**Comment by thebunnyrules** [comment]
Yes, the native window switcher appears (the default shell one). It does not have any launchers. I installed it initially from github, if I remember correctly I had to use make? Today, I used gnome's website.

**Comment by dsboger-zz** [comment]
Could you try this extension and tell me if it works: https://extensions.gnome.org/extension/1133/supertab-launcher/

**Comment by thebunnyrules** [comment]
sure. I'll do so now.

**Comment by thebunnyrules** [comment]
Actually, that's the page I installed from today. I have it installed already.

**Comment by dsboger-zz** [comment]
There are two extensions that add launchers, one for the [App Switcher](https://extensions.gnome.org/extension/1133/supertab-launcher/) and the other for the [Window Switcher](https://extensions.gnome.org/extension/1343/window-switcher-launcher/). Which one are you using (maybe both)?

**Comment by thebunnyrules** [comment]
I see. I'm using the Windows Switcher and you want me to try the App Switcher. Ok. I'll give it a go.

**Comment by thebunnyrules** [comment]
Ah, the App Switcher is working. I see the launcher icons. What's difference between the Window and App version?

**Comment by thebunnyrules** [comment]
Thanks alot for your help. :+1:  :)

**Comment by dsboger-zz** [comment]
Window switcher is disabled by default in GNOME Shell, but you can assign a keybinding to it from the control center.

![image](https://user-images.githubusercontent.com/2356842/37009000-94769f8c-20c3-11e8-941f-6ae421bd2eed.png)

The difference is that the Window switcher switches between windows, without grouping by app. Check the screenshots on the two extensions pages and you'll see.

**Comment by thebunnyrules** [comment]
Wow, that's pretty neat. Thanks, I learned something new.
